Index: makefile
===================================================================
--- makefile.orig	2019-03-01 17:31:46.979807283 +0000
+++ makefile	2019-03-01 17:42:03.314314016 +0000
@@ -387,10 +387,11 @@ endif
 
 # install the python scripts
 install_py_scripts:
+	cd ofed_scripts/utils && $(MLNX_PYTHON) setup.py build --executable=/usr/bin/python && cd -
 ifeq ($(RECORD_PY_FILES),1)
-	cd ofed_scripts/utils && $(MLNX_PYTHON) setup.py install -O1 --root=$(INSTALL_MOD_PATH) --record ../../../../ofed-files && cd -
+	cd ofed_scripts/utils && $(MLNX_PYTHON) setup.py install -O1 --root=$(INSTALL_MOD_PATH) --record ../../../../ofed-files --skip-build && cd -
 else
-	cd ofed_scripts/utils && $(MLNX_PYTHON) setup.py install -O1 --root=$(INSTALL_MOD_PATH)/ && cd -
+	cd ofed_scripts/utils && $(MLNX_PYTHON) setup.py install -O1 --root=$(INSTALL_MOD_PATH)/ --skip-build && cd -
 endif
 
 
